version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "com.github.ben-manes.caffeine:caffeine"
      - dependency-name: "org.junit:junit-bom"