
description = 'Delivery4j'

allprojects {
    if (project.name == 'broker') {
        return
    }

    apply plugin: 'java'
    apply plugin: 'idea'
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'

    apply from: "$rootDir/gradle/publish-config.gradle"

    idea {
        module {
            downloadJavadoc = true
            downloadSources = true
        }
    }

    repositories {
        mavenCentral()
    }

    dependencies {
        compileOnly 'org.jetbrains:annotations:26.1.0'
    }

    compileJava {
        options.encoding = 'UTF-8'
    }

    java {
        toolchain.languageVersion.set(JavaLanguageVersion.of(8))
        withSourcesJar()
        withJavadocJar()
    }

    javadoc {
        options {
            links 'https://docs.oracle.com/en/java/javase/11/docs/api/'
            links 'https://javadoc.io/doc/org.jetbrains/annotations/latest/'
        }
    }

    publishing {
        publications {
            maven(MavenPublication) {
                from components.java

                pom {
                    afterEvaluate {
                        description = 'Java library facade for multiple data delivery concepts'
                    }
                }
            }
        }
    }
}

subprojects {
    if (project.name == 'broker') {
        return
    }

    dependencies {
        implementation rootProject
    }

    publishing {
        publications {
            maven(MavenPublication) {
                artifactId = 'delivery4j-' + project.name

                pom {
                    afterEvaluate {
                        description = "Module \"${project.name}\" of Delivery4j"
                    }
                }
            }
        }
    }
}

dependencies {
    compileOnly('org.apache.logging.log4j:log4j-api:2.25.4') { transitive = false }
    compileOnly('org.slf4j:slf4j-api:2.0.17') { transitive = false }

    testImplementation(platform('org.junit:junit-bom:5.14.3'))
    testImplementation('org.junit.jupiter:junit-jupiter')
    testRuntimeOnly('org.junit.platform:junit-platform-launcher')

    testImplementation 'org.jetbrains:annotations:26.1.0'
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}

javadoc {
    options {
        links 'https://logging.apache.org/log4j/2.x/javadoc/log4j-api/'
        links 'https://slf4j.org/api/'
    }
}

def javadocProjects= [
        ':',
        ':broker:broker-activemq',
        ':broker:broker-kafka',
        ':broker:broker-nats',
        ':broker:broker-postgresql',
        ':broker:broker-postgresql-hikari',
        ':broker:broker-rabbitmq',
        ':broker:broker-redis-jedis',
        ':broker:broker-redis-lettuce',
        ':broker:broker-sql',
        ':broker:broker-sql-hikari',
        ':broker:broker-valkey'
]

tasks.register('allJavadoc', Javadoc) {
    group = 'documentation'

    source javadocProjects.collect { project(it).sourceSets.main.allJava }
    classpath = files(javadocProjects.collect { project(it).sourceSets.main.compileClasspath })
    javadocTool.set(javaToolchains.javadocToolFor {
        languageVersion.set(JavaLanguageVersion.of(25))
    })

    options {
        // Java
        links 'https://docs.oracle.com/en/java/javase/11/docs/api/'

        // Broker
        links 'https://javadoc.io/doc/org.apache.activemq/activemq-client/latest/'
        links 'https://javadoc.io/doc/org.apache.kafka/kafka-clients/latest/'
        links 'https://javadoc.io/doc/io.nats/jnats/latest/'
        links 'https://javadoc.io/doc/org.postgresql/postgresql/latest/'
        links 'https://rabbitmq.github.io/rabbitmq-java-client/api/current/'
        links 'https://javadoc.io/doc/redis.clients/jedis/latest/'
        links 'https://javadoc.io/doc/io.lettuce/lettuce-core/latest/'
        links 'https://javadoc.io/doc/com.zaxxer/HikariCP/latest/'
        links 'https://javadoc.io/doc/io.valkey/valkey-java/latest/'

        // Common
        links 'https://logging.apache.org/log4j/2.x/javadoc/log4j-api/'
        links 'https://slf4j.org/api/'
        links 'https://javadoc.io/doc/org.jetbrains/annotations/latest/'
    }
    destinationDir = file(project.layout.buildDirectory.dir('docs/all-javadoc'))
}
