description = 'Delivery4j Broker ActiveMQ'

dependencies {
    api 'org.apache.activemq:activemq-client:6.2.4'
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(17))
}

javadoc {
    options {
        links 'https://javadoc.io/doc/org.apache.activemq/activemq-client/latest/'
    }
}